[package]
name = "myserver"
version = "0.1.0"
authors = ["kenneth.marete <maretekent@gmail.com>"]
edition = "2018"

[dependencies]
getopts = "0.2.19"
num_cpus = "1"
scoped_threadpool = "0.1.9"
http-muncher = "0.3.2"
httparse="1.3.4"
